### ISSUE TITLE
model mstl cant be period=1

### ISSUE THREAD

**Issue by rizal-mujahiddan69** [Nixtla/statsforecast#411] opened 2023-02-18 12:06 UTC
### mstl cant be period  = 1

File c:\Users\BlaBlaBla\.conda\envs\ml\lib\site-packages\statsforecast\mstl.py:59, in mstl(x, period, blambda, iterate, s_window)
     57 if msts is not None:
     58     if len(msts) == 1:
---> 59         output["seasonal"] = seas[0]
     60     else:
     61         for i, seas_ in enumerate(msts, start=0):

UnboundLocalError: local variable 'seas' referenced before assignment

### Versions / Dependencies

StatsForecast 1.40 , Python 3.9.15, os Windows 11

### Reproduction script

from statsmodels.tsa.seasonal import seasonal_decompose
from statsforecast.models import mstl

tabel_emas_decom = tabel_emas_kurs_inflasi_interest.copy()
tabel_emas_decom.tanggal = pd.to_datetime(tabel_emas_decom.tanggal)
tabel_emas_decom.set_index('tanggal',inplace=True)
tabel_emas_decom = tabel_emas_decom[~(tabel_emas_decom.index.duplicated())]
tabel_emas_decom = tabel_emas_decom.asfreq('D')

data_emas = tabel_emas_decom.harga_emas.to_numpy()
data_emas = data_emas[~np.isnan(data_emas)]

# data_emas = mstl(data_emas,period=[1,365,365*5],iterate=10)
data_emas = mstl(data_emas,period=1,iterate=10)
print(data_emas)

plt.plot(data_emas.trend)
plt.title('trend')
plt.show()

plt.plot(data_emas.seasonal365)
plt.title('Seasonal 1 Tahun')
plt.show()

plt.plot(data_emas.seasonal1825)
plt.title('Seasonal 5 Tahun')
plt.show()

(Im already install library SuperSmooth)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by FedericoGarza** [comment] 2023-04-06 02:06
hey @rizal-mujahiddan69! Thanks for using statsforecast.

The issue should be fixed by #463. 

When `period=1`, or in your case `period=[1,365,365*5]`, the `mstl` function will only compute the trend component and not the seasonal components. This is the expected behavior since it will consider the first value (`1`) as an option to only calculate the trend. To compute the trend and seasonal components you can use `period=[365, 365*5]`.

**Closed** 2023-04-06 15:08 UTC
Labels: bug
