### ISSUE TITLE
 [Core] Make StatsForecast.forecast_fitted_values() possible when using a Fugue backend

### ISSUE THREAD

**Issue by wregter** [Nixtla/statsforecast#382] opened 2023-01-04 10:12 UTC
### Description

When using StatsForecast.forecast_fitted_values() while the backend parameter in the StatsForecast object is set to my Fugue backend, I get the following error:
NotImplementedError: Execution with a distributed backend only supports `forecast` and `cross_validation` methods. Try setting the backend parameter to None.

### Use case

I would like to use StatsForecast.forecast_fitted_values() with my Fugue backend so I can use the fitted values in reconciliation approaches provided by the hierarchicalforecast package, while training the models for the hierarchy quickly using Spark.

**Comment by alexeyegorov** [comment] 2023-05-11 11:46
Duplicate of #454

**Closed** 2023-10-19 16:16 UTC
